name: PHPUnit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: upi
          MYSQL_PASSWORD: 12345678
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-start-period=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, sqlite3, pdo_mysql
        coverage: xdebug

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

    - name: Copy .env file
      run: |
        cp .env.example .env

    - name: Generate APP_KEY
      run: |
        php artisan key:generate

    - name: Run PHPUnit tests
      run: |
        php artisan migrate --env=testing
        php artisan db:seed --env=testing
        ./vendor/bin/phpunit --configuration phpunit.xml --testdox
